# YOLOv5 🚀 by Ultralytics https://ultralytics.com, licensed under GNU GPL v3.0
# COCO128 dataset https://www.kaggle.com/ultralytics/coco128 (first 128 images from COCO train2017)
# Example usage: python train.py --data coco128.yaml
# parent
# ├── yolov5
# └── datasets
#     └── coco128  ← downloads here


# Train/val/test sets as 1) dir: path/to/imgs, 2) file: path/to/imgs.txt, or 3) list: [path/to/imgs1, path/to/imgs2, ..]
#path: /home/dm/data3/dataset/face_person/MPII  # dataset root dir
#train: /home/dm/data3/dataset/face_person/MPII/test1.txt  # train images (relative to 'path') 128 images
#val: /home/dm/data3/dataset/face_person/MPII/test1.txt  # val images (relative to 'path') 128 images
path: ""  # dataset root dir
#train:
#- "/data3/panjinquan/dataset/face_person/MPII/trainval.txt"
#- "/data3/panjinquan/dataset/face_person/VOCdevkit/VOC2012/trainval.txt"
#- "/data3/panjinquan/dataset/face_person/VOCdevkit/VOC2007/trainval.txt"
#- "/data3/panjinquan/dataset/face_person/COCO/VOC/trainval.txt"
#- "/data3/panjinquan/dataset/face_person/SMTC/trainval.txt"
#val: "/data3/panjinquan/dataset/face_person/MPII/test.txt"

# ATP: /atpcephdata/panjinquan/dataset/face_person
train:
- "panjinquan/dataset/face_person/MPII/trainval.txt"
- "panjinquan/dataset/face_person/VOCdevkit/VOC2012/trainval.txt"
- "panjinquan/dataset/face_person/VOCdevkit/VOC2007/trainval.txt"
- "panjinquan/dataset/face_person/COCO/VOC/trainval.txt"
- "panjinquan/dataset/face_person/SMTC/trainval.txt"

val: "panjinquan/dataset/face_person/MPII/test.txt"

test:  # test images (optional)
data_type: voc

# Classes
nc: 2  # number of classes
names: [ 'face','person' ]  # class names


# Download script/URL (optional)
#download: https://github.com/ultralytics/yolov5/releases/download/v1.0/coco128.zip