train_data:
  - '/home/dm/nasdata/dataset/csdn/plate/dataset/CCPD2020-voc/train/plates'
  - '/home/dm/nasdata/dataset/csdn/plate/dataset/CCPD2020-voc/val/plates'
  - '/home/dm/nasdata/dataset/csdn/plate/dataset/CCPD2019-voc/ccpd_base/plates-train'
  - '/home/dm/nasdata/dataset/csdn/plate/dataset/CCPD2019-voc/ccpd_blur/plates'
  - '/home/dm/nasdata/dataset/csdn/plate/dataset/CCPD2019-voc/ccpd_challenge/plates'
  - '/home/dm/nasdata/dataset/csdn/plate/dataset/CCPD2019-voc/ccpd_db/plates'
  - '/home/dm/nasdata/dataset/csdn/plate/dataset/CCPD2019-voc/ccpd_fn/plates'
  - '/home/dm/nasdata/dataset/csdn/plate/dataset/CCPD2019-voc/ccpd_rotate/plates'
  - '/home/dm/nasdata/dataset/csdn/plate/dataset/CCPD2019-voc/ccpd_tilt/plates'
  - '/home/dm/nasdata/dataset/csdn/plate/dataset/CCPD2019-voc/ccpd_weather/plates'

test_data:
  - '/home/dm/nasdata/dataset/csdn/plate/dataset/CCPD2020-voc/test/plates'
  - '/home/dm/nasdata/dataset/csdn/plate/dataset/CCPD2019-voc/ccpd_base/plates-test'

class_name: "data/plates_table.txt"
train_transform: "train"
test_transform: "test"
batch_size: 64
net_type: 'CRNN'
flag: "Perspective"
input_size: [ 160, 32 ]
rgb_mean: [ 0.5, 0.5, 0.5 ]
rgb_std: [ 0.5, 0.5, 0.5 ]
resample: True
work_dir: "work_space"
num_epochs: 200
optim_type: 'Adam'
lr: 0.001
weight_decay: 0.0
milestones: [ 100,150,170 ]
momentum: 0.0
gpu_id: [ 0 ]
num_workers: 8
log_freq: 20
pretrained: "data/pretrained/CRNN/CRNN.pth"
